# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
spring:
  application:
    name: training-tracker
  jackson:
    default-property-inclusion: always
  datasource:
    url: jdbc:postgresql://localhost:5432/training_tracker
    username: noslen
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.nelsonjohns.com/realms/admin
management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true
