# spring.application.name=training-tracker

# # Configure Jackson to always include null values in JSON serialization
# spring.jackson.default-property-inclusion=always

# # Configure PostgreSQL database
# spring.datasource.url=jdbc:postgresql://localhost:5432/training_tracker
# spring.datasource.username=postgres
# spring.datasource.password=postgres
# spring.datasource.driver-class-name=org.postgresql.Driver

# # Configure JPA
# spring.jpa.show-sql=true
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# # Configure OAuth2 Resource Server
