-- V1 baseline schema for training-tracker.
--
-- Generated from the JPA entity model via Hibernate schema export (jakarta.persistence
-- schema-generation), so it is the canonical, drift-free schema that `ddl-auto: validate`
-- checks the running DB against. Replaces the old `ddl-auto: update` approach, which had
-- accumulated a stale FK (day_exercises.muscle_group_id -> day_muscle_groups) that this
-- baseline intentionally does NOT contain.
--
-- Existing databases are adopted via spring.flyway.baseline-on-migrate=true (marked at V1
-- without re-running this script); fresh databases have this applied by Flyway on first boot.

    create table day_exercises (
        joint_pain integer,
        position integer,
        created_at timestamp(6) with time zone,
        day_id bigint,
        exercise_id bigint,
        id bigint generated by default as identity,
        muscle_group_id bigint,
        source_day_exercise_id bigint,
        updated_at timestamp(6) with time zone,
        status varchar(255) check (status in ('COMPLETE','EMPTY','PARTIAL','PENDING','PENDING_CONFIRMATION','PENDING_FEEDBACK','PENDING_WEIGHT','PROGRAMMED','READY','SKIPPED','UNPROGRAMMED')),
        primary key (id)
    );

    create table day_muscle_groups (
        pump integer,
        recommended_sets integer,
        soreness integer,
        workload integer,
        created_at timestamp(6) with time zone,
        day_id bigint,
        id bigint generated by default as identity,
        muscle_group_id bigint,
        updated_at timestamp(6) with time zone,
        status varchar(255) check (status in ('COMPLETE','EMPTY','PARTIAL','PENDING','PENDING_CONFIRMATION','PENDING_FEEDBACK','PENDING_WEIGHT','PROGRAMMED','READY','SKIPPED','UNPROGRAMMED')),
        primary key (id)
    );

    create table day_notes (
        pinned boolean,
        created_at timestamp(6) with time zone,
        day_id bigint,
        id bigint generated by default as identity,
        note_id bigint,
        updated_at timestamp(6) with time zone,
        text varchar(255),
        primary key (id)
    );

    create table days (
        bodyweight float(53),
        position integer,
        unit smallint check (unit between 0 and 1),
        week integer,
        bodyweight_at timestamp(6) with time zone,
        created_at timestamp(6) with time zone,
        finished_at timestamp(6) with time zone,
        id bigint generated by default as identity,
        meso_id bigint,
        updated_at timestamp(6) with time zone,
        label varchar(255),
        primary key (id)
    );

    create table exercise_notes (
        created_at timestamp(6) with time zone,
        day_exercise_id bigint,
        exercise_id bigint,
        id bigint generated by default as identity,
        note_id bigint,
        updated_at timestamp(6) with time zone,
        user_id bigint,
        text varchar(255),
        primary key (id)
    );

    create table exercise_sets (
        bodyweight float4,
        position integer,
        reps integer,
        reps_target integer,
        weight float4,
        weight_target float4,
        weight_target_max float4,
        weight_target_min float4,
        created_at timestamp(6) with time zone,
        day_exercise_id bigint,
        finished_at timestamp(6) with time zone,
        id bigint generated by default as identity,
        set_type varchar(255) check (set_type in ('REGULAR','MYOREP','MYOREP_MATCH')),
        status varchar(255) check (status in ('COMPLETE','EMPTY','PARTIAL','PENDING','PENDING_CONFIRMATION','PENDING_FEEDBACK','PENDING_WEIGHT','PROGRAMMED','READY','SKIPPED','UNPROGRAMMED')),
        unit varchar(255) check (unit in ('KG','LB')),
        primary key (id)
    );

    create table exercises (
        created_at timestamp(6) with time zone,
        deleted_at timestamp(6) with time zone,
        id bigint generated by default as identity,
        muscle_group_id bigint,
        updated_at timestamp(6) with time zone,
        user_id bigint,
        exercise_type varchar(255) check (exercise_type in ('BARBELL','BODYWEIGHT_ONLY','BODYWEIGHT_LOADABLE','CABLE','DUMBBELL','FREEMOTION','MACHINE','MACHINE_ASSISTANCE','SMITH_MACHINE')),
        mg_sub_type varchar(255) check (mg_sub_type in ('COMPOUND','CURL','HEAVY_AXIAL','HINGE','HORIZONTAL','INCLINE','NON_HEAVY_AXIAL','NON_INCLINE','NON_OVERHEAD','OVERHEAD','RAISE','VERTICAL')),
        name varchar(255),
        youtube_id varchar(255),
        primary key (id)
    );

    create table meso_notes (
        created_at timestamp(6) with time zone,
        id bigint generated by default as identity,
        mesocycle_id bigint,
        note_id bigint,
        updated_at timestamp(6) with time zone,
        user_id bigint,
        text varchar(255),
        primary key (id)
    );

    create table mesocycles (
        days integer,
        unit smallint check (unit between 0 and 1),
        created_at timestamp(6) with time zone,
        deleted_at timestamp(6) with time zone,
        finished_at timestamp(6) with time zone,
        first_exercise_completed_at timestamp(6) with time zone,
        first_micro_completed_at timestamp(6) with time zone,
        first_set_completed_at timestamp(6) with time zone,
        first_workout_completed_at timestamp(6) with time zone,
        id bigint generated by default as identity,
        last_micro_finished_at timestamp(6) with time zone,
        last_set_completed_at timestamp(6) with time zone,
        last_set_skipped_at timestamp(6) with time zone,
        last_workout_completed_at timestamp(6) with time zone,
        last_workout_finished_at timestamp(6) with time zone,
        last_workout_partialed_at timestamp(6) with time zone,
        last_workout_skipped_at timestamp(6) with time zone,
        micro_rirs bigint,
        source_meso_id bigint,
        source_template_id bigint,
        updated_at timestamp(6) with time zone,
        user_id bigint,
        generated_from varchar(255),
        meso_key varchar(255),
        name varchar(255),
        status varchar(255) check (status in ('COMPLETE','EMPTY','PARTIAL','PENDING','PENDING_CONFIRMATION','PENDING_FEEDBACK','PENDING_WEIGHT','PROGRAMMED','READY','SKIPPED','UNPROGRAMMED')),
        primary key (id)
    );

    create table muscle_groups (
        created_at timestamp(6) with time zone,
        id bigint generated by default as identity,
        updated_at timestamp(6) with time zone,
        name varchar(255) check (name in ('CHEST','BACK','TRICEPS','BICEPS','SHOULDERS','QUADS','GLUTES','HAMSTRINGS','CALVES','TRAPS','FOREARMS','ABS')),
        primary key (id)
    );

    create table progressions (
        id bigint generated by default as identity,
        mesocycle_id bigint,
        muscle_group_id bigint,
        progressions_key bigint,
        mg_progression_type varchar(255) check (mg_progression_type in ('REGULAR','SECONDARY')),
        primary key (id)
    );

    create table templates (
        frequency integer,
        created_at timestamp(6) with time zone,
        deleted_at timestamp(6) with time zone,
        id bigint generated by default as identity,
        prev_template_id bigint,
        source_meso_id bigint,
        source_template_id bigint,
        updated_at timestamp(6) with time zone,
        user_id bigint,
        emphasis varchar(255),
        name varchar(255),
        sex varchar(255),
        template_key varchar(255),
        primary key (id)
    );

    alter table if exists day_exercises
       add constraint FKh0ctv3csgjjvuw0amx6mhcd68
       foreign key (day_id)
       references days;

    alter table if exists day_exercises
       add constraint FKtoilj79st8w8nkendi65cof1n
       foreign key (exercise_id)
       references exercises;

    alter table if exists day_exercises
       add constraint FKcy0h3uqmaym1vrhjyhu8cug6w
       foreign key (muscle_group_id)
       references muscle_groups;

    alter table if exists day_muscle_groups
       add constraint FK11d73n5wd4e2o1398m0nnge4a
       foreign key (day_id)
       references days;

    alter table if exists day_muscle_groups
       add constraint FKeeqtyo5gu0ra3mi6x5xnfbsnu
       foreign key (muscle_group_id)
       references muscle_groups;

    alter table if exists day_notes
       add constraint FK6a00itwj3s8042ik1swr6c179
       foreign key (day_id)
       references days;

    alter table if exists days
       add constraint FK1yf590umma31ln12pjfn1nb5m
       foreign key (meso_id)
       references mesocycles;

    alter table if exists exercise_notes
       add constraint FK6wk8wf9he786fsxfv9a3abjwm
       foreign key (day_exercise_id)
       references day_exercises;

    alter table if exists exercise_notes
       add constraint FKkxr68p29snk6k68b5pudneptx
       foreign key (exercise_id)
       references exercises;

    alter table if exists exercise_sets
       add constraint FK2u1scqetamjt7tclmydn77mjl
       foreign key (day_exercise_id)
       references day_exercises;

    alter table if exists meso_notes
       add constraint FKpi7cif8o02qknvil9vqxfu86y
       foreign key (mesocycle_id)
       references mesocycles;

    alter table if exists mesocycles
       add constraint FKropsmnpwwxeanlchae0ijpee2
       foreign key (source_meso_id)
       references mesocycles;

    alter table if exists mesocycles
       add constraint FK8jhvuimaqf57s3abirhkkvjga
       foreign key (source_template_id)
       references templates;

    alter table if exists progressions
       add constraint FKhg4xxieprbp9v0k1x7cvsnq5y
       foreign key (mesocycle_id)
       references mesocycles;

    alter table if exists progressions
       add constraint FKbg1ffdtra7ddq16auxwk30eou
       foreign key (muscle_group_id)
       references muscle_groups;

    alter table if exists templates
       add constraint FKdfqpwmgxh384ldu4ht0i9v89e
       foreign key (prev_template_id)
       references templates;

    alter table if exists templates
       add constraint FKnhpa38vxff238g0he4wrh1eia
       foreign key (source_meso_id)
       references mesocycles;

    alter table if exists templates
       add constraint FK5392ao738y5fly3mq8wvlnorw
       foreign key (source_template_id)
       references templates;
